# Generated by Django 5.1.6 on 2025-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suraksha', '0004_remove_therapist_user_remove_timeslot_therapist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(max_length=100)),
                ('victim_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proof_files', models.FileField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
    ]
