# Generated by Django 5.1.6 on 2025-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suraksha', '0005_incidentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('parent_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
